# gtk_theme_variant = "dark"

[colors.bright]
black = "#5E5C64"
blue = "#2A7BDE"
cyan = "#33C7DE"
green = "#33DA7A"
magenta = "#C061CB"
red = "#F66151"
white = "#FFFFFF"
yellow = "#E9AD0C"

[colors.normal]
black = "#171421"
blue = "#12488B"
cyan = "#2AA1B3"
green = "#26A269"
magenta = "#A347BA"
red = "#C01C28"
white = "#D0CFCC"
yellow = "#A2734C"

[colors.primary]
background = "#181818"
foreground = "#ffffff"

[font]
builtin_box_drawing = true
size = 10

[font.bold]
family = "source code pro"
style = "Bold"

[font.bold_italic]
family = "source code pro"
style = "Bold Italic"

[font.italic]
family = "source code pro"
style = "Italic"

[font.normal]
family = "source code pro"
style = "Regular"

[window]
title = "Cute Terminal"
